version: 0.2

env:
  variables:
    TF_STATE_BUCKET: "yan-terraform"  # S3 bucket for storing Terraform state
    TF_STATE_KEY: "terraform.tfstate"             # State file location in S3
    TF_REGION: ca-central-1                       # AWS Region
    ACTION: "apply"                               # Default action: 'apply' or 'destroy'

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing AWS CDK CLI..."
      - ls 
      - cd wordpress-app
      - npm install -g aws-cdk  
      - npm install             
      - npm version

  pre_build:
    commands:

  build:
    commands:
      - echo "Building TypeScript code..."
      - npm run build           
      - echo "Synthesizing CloudFormation template..."
      - cdk synth               


  post_build:
    commands:
      - echo "Deploying CDK stack..."
      - cdk deploy --require-approval never  